import {
  CourseStatus,
  Visibility,
  type Course,
} from "gql-generated/gql/graphql";

export const mockCoursesData: Course[] = [
  {
    __typename: "Course",
    category: {
      id: "2323",
      name: "Web Development",
      createdAt: "",
      updatedAt: "",
    },
    createdAt: "2024-12-10T09:15:32Z",
    creator: {
      id: "2323",
      fullName: "EduTech Academy",
      createdAt: "",
      email: "",
      updatedAt: "",
      userName: "",
    },
    creatorID: "org-12345",
    description:
      "A comprehensive introduction to modern web development technologies including HTML, CSS, and JavaScript fundamentals.",
    discountedPrice: 79.99,
    duration: 45,
    enrollments: [],
    extraSettings: [
      {
        key: "allowDownloads",
        value: "true",
      },
      {
        key: "forumEnabled",
        value: "true",
      },
      { key: "certificateOnCompletion", value: "true" },
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?q=80&w=3540&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    id: "dewdew",
    instructors: [
      {
        id: "29121",
        fullName: "Jessica Gardea",
        createdAt: "2023-08-15T14:30:22Z",
        email: "jessica.gardea@edutech.com",
        updatedAt: "2024-06-12T10:45:18Z",
        userName: "jessica_gardea",
      },
      {
        id: "29141",
        fullName: "George Gardea",
        createdAt: "2023-09-05T11:20:45Z",
        email: "george.gardea@edutech.com",
        updatedAt: "2024-07-22T09:15:33Z",
        userName: "george_gardea",
      },
    ],
    level: {
      id: "dede",
      name: "Beginner",
      createdAt: "",
      updatedAt: "",
    },
    maxEnrollments: 500,
    price: 129.99,
    progress: {
      progressPercentage: 20,
      completed: false,
      course: {
        __typename: "Course",
        category: {
          id: "2323",
          name: "Web Development",
          createdAt: "",
          updatedAt: "",
        },
        createdAt: "2024-12-10T09:15:32Z",
        creator: {
          id: "2323",
          fullName: "EduTech Academy",
          createdAt: "",
          email: "",
          updatedAt: "",
          userName: "",
        },
        creatorID: "org-12345",
        description:
          "A comprehensive introduction to modern web development technologies including HTML, CSS, and JavaScript fundamentals.",
        discountedPrice: 79.99,
        duration: 45,
        enrollments: [],
        extraSettings: [
          {
            key: "allowDownloads",
            value: "true",
          },
          {
            key: "forumEnabled",
            value: "true",
          },
          { key: "certificateOnCompletion", value: "true" },
        ],
        featuredImage: "https://example.com/courses/web-dev-basics.jpg",
        id: "dewdew",
        instructors: [
          {
            id: "29121",
            fullName: "Jessica Gardea",
            createdAt: "2023-08-15T14:30:22Z",
            email: "jessica.gardea@edutech.com",
            updatedAt: "2024-06-12T10:45:18Z",
            userName: "jessica_gardea",
          },
          {
            id: "29141",
            fullName: "George Gardea",
            createdAt: "2023-09-05T11:20:45Z",
            email: "george.gardea@edutech.com",
            updatedAt: "2024-07-22T09:15:33Z",
            userName: "george_gardea",
          },
        ],
        level: {
          id: "dede",
          name: "Beginner",
          createdAt: "",
          updatedAt: "",
        },
        maxEnrollments: 500,
        price: 129.99,
        title: "",
        updatedAt: "",
      },
      createdAt: "2025-02-10T08:45:22Z",
      id: "progress-78901",
      startedAt: "2025-02-10T08:45:22Z",
      updatedAt: "2025-03-05T19:30:15Z",
      user: {
        __typename: "User",
        authProvider: "email",
        createdAt: "2024-08-15T10:22:33Z",
        email: "student1@example.com",
        fullName: "Alex Johnson",
        id: "user-56789",
        interests: ["Programming", "Web Design"],
        isActive: true,
        isVerified: true,
        major: "Computer Science",
        occupation: "Student",
        phoneNumber: "+15551234567",
        profilePicture: "https://example.com/users/alex_profile.jpg",
        role: "student",
        socialId: null,
        stripeId: "cus_AB12345CDE",
        updatedAt: "2025-01-30T15:45:22Z",
        userName: "alex_j",
      },
    },
    promotionDuration: 9,
    publishedAt: "2024-12-15T00:00:00Z",
    requirements: "Basic computer skills, Internet connection",
    reviews: [],
    scheduledPublishAt: "2024-12-15T00:00:00Z",
    status: CourseStatus.Published,
    tags: ["HTML", "CSS", "JavaScript", "Web Development"],
    title: "Curso de prueba",
    topics: [
      {
        lessons: [
          {
            id: "666",
            createdAt: "2024-11-05T15:30:22Z",
            title: "Introduction to HTML Structure",
            updatedAt: "2024-12-01T09:15:30Z",
          },
          {
            id: "667",
            createdAt: "2024-11-05T16:45:10Z",
            title: "CSS Styling Basics",
            updatedAt: "2024-12-01T10:20:15Z",
          },
          {
            id: "668",
            createdAt: "2024-11-06T09:30:45Z",
            title: "JavaScript Fundamentals",
            updatedAt: "2024-12-02T14:30:22Z",
          },
        ],
        course: {
          __typename: "Course",
          category: {
            id: "2323",
            name: "Web Development",
            createdAt: "",
            updatedAt: "",
          },
          createdAt: "2024-12-10T09:15:32Z",
          creator: {
            id: "2323",
            fullName: "EduTech Academy",
            createdAt: "",
            email: "",
            updatedAt: "",
            userName: "",
          },
          creatorID: "org-12345",
          description:
            "A comprehensive introduction to modern web development technologies including HTML, CSS, and JavaScript fundamentals.",
          discountedPrice: 79.99,
          duration: 45,
          enrollments: [],
          extraSettings: [
            {
              key: "allowDownloads",
              value: "true",
            },
            {
              key: "forumEnabled",
              value: "true",
            },
            { key: "certificateOnCompletion", value: "true" },
          ],
          featuredImage: "https://example.com/courses/web-dev-basics.jpg",
          id: "dewdew",
          instructors: [
            {
              id: "29121",
              fullName: "Jessica Gardea",
              createdAt: "2023-08-15T14:30:22Z",
              email: "jessica.gardea@edutech.com",
              updatedAt: "2024-06-12T10:45:18Z",
              userName: "jessica_gardea",
            },
            {
              id: "29141",
              fullName: "George Gardea",
              createdAt: "2023-09-05T11:20:45Z",
              email: "george.gardea@edutech.com",
              updatedAt: "2024-07-22T09:15:33Z",
              userName: "george_gardea",
            },
          ],
          level: {
            id: "dede",
            name: "Beginner",
            createdAt: "",
            updatedAt: "",
          },
          maxEnrollments: 500,
          price: 129.99,
          title: "",
          updatedAt: "",
        },
        createdAt: "2024-11-01T10:15:30Z",
        id: "topic-12345",
        updatedAt: "2024-12-05T16:30:22Z",
      },
      {
        lessons: [
          {
            id: "669",
            createdAt: "2024-11-08T11:20:30Z",
            title: "Responsive Design Principles",
            updatedAt: "2024-12-03T15:45:20Z",
          },
          {
            id: "670",
            createdAt: "2024-11-09T14:15:45Z",
            title: "Mobile-First Development",
            updatedAt: "2024-12-04T09:30:15Z",
          },
        ],
        course: {
          __typename: "Course",
          category: {
            id: "2323",
            name: "Web Development",
            createdAt: "",
            updatedAt: "",
          },
          createdAt: "2024-12-10T09:15:32Z",
          creator: {
            id: "2323",
            fullName: "EduTech Academy",
            createdAt: "",
            email: "",
            updatedAt: "",
            userName: "",
          },
          creatorID: "org-12345",
          description:
            "A comprehensive introduction to modern web development technologies including HTML, CSS, and JavaScript fundamentals.",
          discountedPrice: 79.99,
          duration: 45,
          enrollments: [],
          extraSettings: [
            {
              key: "allowDownloads",
              value: "true",
            },
            {
              key: "forumEnabled",
              value: "true",
            },
            { key: "certificateOnCompletion", value: "true" },
          ],
          featuredImage: "https://example.com/courses/web-dev-basics.jpg",
          id: "dewdew",
          instructors: [
            {
              id: "29121",
              fullName: "Jessica Gardea",
              createdAt: "2023-08-15T14:30:22Z",
              email: "jessica.gardea@edutech.com",
              updatedAt: "2024-06-12T10:45:18Z",
              userName: "jessica_gardea",
            },
            {
              id: "29141",
              fullName: "George Gardea",
              createdAt: "2023-09-05T11:20:45Z",
              email: "george.gardea@edutech.com",
              updatedAt: "2024-07-22T09:15:33Z",
              userName: "george_gardea",
            },
          ],
          level: {
            id: "dede",
            name: "Beginner",
            createdAt: "",
            updatedAt: "",
          },
          maxEnrollments: 500,
          price: 129.99,
          title: "",
          updatedAt: "",
        },
        createdAt: "2024-11-07T09:10:15Z",
        id: "topic-12346",
        updatedAt: "2024-12-06T14:35:40Z",
      },
    ],
    updatedAt: "2025-01-18T14:22:45Z",
    video: {
      id: "767",
      videoURL: "https://example.com/videos/web-dev-intro.mp4",
      createdAt: "",
      updatedAt: "",
    },
    visibility: Visibility.Public,
  },
  {
    __typename: "Course",
    category: {
      id: "2324",
      name: "Data Science",
      createdAt: "",
      updatedAt: "",
    },
    createdAt: "2024-11-15T10:20:45Z",
    creator: {
      id: "2324",
      fullName: "Tech Institute",
      createdAt: "",
      email: "",
      updatedAt: "",
      userName: "",
    },
    creatorID: "org-12346",
    description:
      "Master Python programming and data analysis with real-world projects and practical examples.",
    discountedPrice: 89.99,
    duration: 60,
    enrollments: [],
    extraSettings: [
      { key: "allowDownloads", value: "true" },
      { key: "forumEnabled", value: "true" },
      { key: "certificateOnCompletion", value: "true" },
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1528158222524-d4d912d2e208?q=80&w=3480&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    id: "course-789",
    instructors: [
      {
        id: "29122",
        fullName: "Maria Rodriguez",
        createdAt: "2023-09-15T15:30:22Z",
        email: "maria.rodriguez@techinstitute.com",
        updatedAt: "2024-07-12T11:45:18Z",
        userName: "maria_rodriguez",
      },
    ],
    level: {
      id: "level-2",
      name: "Intermediate",
      createdAt: "",
      updatedAt: "",
    },
    maxEnrollments: 300,
    price: 149.99,
    progress: undefined,
    promotionDuration: 7,
    publishedAt: "2024-11-20T00:00:00Z",
    requirements: "Basic Python knowledge, Mathematics fundamentals",
    reviews: [],
    scheduledPublishAt: "2024-11-20T00:00:00Z",
    status: CourseStatus.Published,
    tags: ["Python", "Data Science", "Machine Learning"],
    title: "Python for Data Science",
    topics: [],
    updatedAt: "2025-01-20T16:30:45Z",
    video: {
      id: "768",
      videoURL: "https://example.com/videos/data-science-intro.mp4",
      createdAt: "",
      updatedAt: "",
    },
    visibility: Visibility.Public,
  },
  {
    __typename: "Course",
    category: {
      id: "2325",
      name: "Mobile Development",
      createdAt: "",
      updatedAt: "",
    },
    createdAt: "2024-10-20T11:30:45Z",
    creator: {
      id: "2325",
      fullName: "Mobile Academy",
      createdAt: "",
      email: "",
      updatedAt: "",
      userName: "",
    },
    creatorID: "org-12347",
    description:
      "Learn to build modern iOS applications using Swift and SwiftUI framework.",
    discountedPrice: 69.99,
    duration: 50,
    enrollments: [],
    extraSettings: [
      { key: "allowDownloads", value: "true" },
      { key: "forumEnabled", value: "true" },
      { key: "certificateOnCompletion", value: "true" },
    ],
    featuredImage:
      "https://images.unsplash.com/photo-1581287053822-fd7bf4f4bfec?q=80&w=3601&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    id: "course-790",
    instructors: [
      {
        id: "29123",
        fullName: "David Chen",
        createdAt: "2023-10-15T16:30:22Z",
        email: "david.chen@mobileacademy.com",
        updatedAt: "2024-08-12T12:45:18Z",
        userName: "david_chen",
      },
    ],
    level: {
      id: "level-3",
      name: "Advanced",
      createdAt: "",
      updatedAt: "",
    },
    maxEnrollments: 250,
    price: 159.99,
    progress: null,
    promotionDuration: 5,
    publishedAt: "2024-10-25T00:00:00Z",
    requirements: "Mac computer, Basic programming knowledge",
    reviews: [],
    scheduledPublishAt: "2024-10-25T00:00:00Z",
    status: CourseStatus.Published,
    tags: ["iOS", "Swift", "SwiftUI", "Mobile Development"],
    title: "iOS Development with Swift",
    topics: [],
    updatedAt: "2025-01-22T17:45:45Z",
    video: {
      id: "769",
      videoURL: "https://example.com/videos/ios-dev-intro.mp4",
      createdAt: "",
      updatedAt: "",
    },
    visibility: Visibility.Public,
  },
];
